# Generated by Django 4.1.6 on 2023-02-07 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('shared_at', models.DateTimeField(blank=True, null=True)),
                ('worskshop_title', models.CharField(max_length=100)),
                ('uses', models.CharField(choices=[('BUSINESS_CREATION', 'Business Creation'), ('POST_CREATION', 'Post Creation')], default='Post Creation', max_length=100)),
                ('target_skills', models.CharField(choices=[('COMPUTER_SKILLS', 'Computer Skills'), ('NUMERACY_SKILLS', 'Numeracy Skills')], default='Computer Skills', max_length=100)),
                ('duration', models.IntegerField()),
                ('workshop_method', models.CharField(choices=[('ONLINE', 'Online'), ('BLENDED', 'Blended'), ('PRESENTIAL', 'Presential')], default='Online', max_length=100)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
