# Generated by Django 4.1.6 on 2023-04-12 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('shared_at', models.DateTimeField(blank=True, null=True)),
                ('workshop_title', models.CharField(max_length=100, null=True)),
                ('uses', models.CharField(choices=[('Business Creation', 'Business Creation'), ('Post Creation', 'Post Creation'), ('Agriculture Business', 'Agriculture Business'), ('Startups', 'Startups'), ('Social Business', 'Social Business'), ('Green Business', 'Green Business'), ('Women Entrepreneurship', 'Women Entrepreneurship')], default='Post Creation', max_length=100, null=True)),
                ('target_skills', models.CharField(choices=[('Computer Skills', 'Computer Skills'), ('Numeracy Skills', 'Numeracy Skills')], default='Computer Skills', max_length=100, null=True)),
                ('duration', models.PositiveIntegerField(null=True)),
                ('workshop_method', models.CharField(choices=[('Online', 'Online'), ('Blended', 'Blended'), ('Presential', 'Presential')], default='Online', max_length=100, null=True)),
                ('workshop_image', models.ImageField(null=True, upload_to='workshopimages/')),
                ('workshop_description', models.TextField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_share_workshop', 'Can share workshop')],
                'get_latest_by': 'created_at',
            },
        ),
    ]
