# Generated by Django 4.1.6 on 2023-04-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='workshop_attachements',
            field=models.FileField(null=True, upload_to='workshopattachements/'),
        ),
    ]
