# Generated by Django 4.1.6 on 2023-02-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_alter_workshop_uses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop',
            old_name='worskshop_title',
            new_name='workshop_title',
        ),
        migrations.AlterField(
            model_name='workshop',
            name='uses',
            field=models.CharField(choices=[('BUSINESS_CREATION', 'Business Creation'), ('POST_CREATION', 'Post Creation'), ('AGRICULTURE_BUSINESS', 'Agriculture Business'), ('STARTUPS', 'Startups'), ('SOCIAL_BUSINESS', 'Social Business'), ('GREEN_BUSINESS', 'Green Business'), ('WOMEN_ENTREPRENEURSHIP', 'Women Entrepreneurship')], default='Post Creation', max_length=100),
        ),
    ]
