# Generated by Django 4.1.6 on 2023-02-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_workshop_workshop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='workshop_image',
            field=models.ImageField(null=True, upload_to='workshopimages/'),
        ),
    ]
