# Generated by Django 4.1.6 on 2023-02-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_alter_workshop_workshop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
    ]
