# Generated by Django 4.1.6 on 2023-04-13 22:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_alter_workshop_workshop_attachements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='workshop_attachements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(null=True, upload_to='workshopattachements/'), null=True, size=None),
        ),
    ]
