# Generated by Django 4.1.6 on 2023-04-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_alter_workshop_workshop_attachements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='workshop_attachements',
            field=models.FileField(null=True, upload_to='workshopattachements/'),
        ),
    ]
