# Generated by Django 4.1.6 on 2023-02-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_alter_workshop_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='workshop_description',
            field=models.TextField(null=True),
        ),
    ]
