# Generated by Django 4.1.6 on 2023-02-11 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0007_workshop_workshop_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='workshop_image',
        ),
    ]
