# Generated by Django 4.1.6 on 2023-04-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0007_alter_workshop_workshop_attachements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='workshop_image',
            field=models.ImageField(null=True, upload_to='workshopattachements/'),
        ),
    ]
