# Generated by Django 4.1.6 on 2023-02-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0011_remove_workshop_workshop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='workshop_image',
            field=models.ImageField(null=True, upload_to='workshopimages/'),
        ),
    ]
