# Generated by Django 4.1.6 on 2023-02-12 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0012_workshop_workshop_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='shared_at',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='shared_by',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='shared_with',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='updated_by',
        ),
    ]
