# Generated by Django 4.1.6 on 2023-02-12 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0014_workshop_created_at_workshop_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='workshop_image',
        ),
    ]
