# Generated by Django 4.1.6 on 2023-02-13 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0016_workshop_workshop_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='workshop_image',
        ),
    ]
