# Generated by Django 4.1.6 on 2023-02-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0019_remove_workshop_workshop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='target_skills',
            field=models.CharField(choices=[('COMPUTER_SKILLS', 'Computer Skills'), ('NUMERACY_SKILLS', 'Numeracy Skills')], default='Computer Skills', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='uses',
            field=models.CharField(choices=[('BUSINESS_CREATION', 'Business Creation'), ('POST_CREATION', 'Post Creation'), ('AGRICULTURE_BUSINESS', 'Agriculture Business'), ('STARTUPS', 'Startups'), ('SOCIAL_BUSINESS', 'Social Business'), ('GREEN_BUSINESS', 'Green Business'), ('WOMEN_ENTREPRENEURSHIP', 'Women Entrepreneurship')], default='Post Creation', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='workshop_method',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('BLENDED', 'Blended'), ('PRESENTIAL', 'Presential')], default='Online', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='workshop_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
