# Generated by Django 4.1.6 on 2023-02-28 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0020_alter_workshop_target_skills_alter_workshop_uses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='duration',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
