# Generated by Django 4.1.6 on 2023-03-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0021_alter_workshop_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='target_skills',
            field=models.CharField(choices=[('Computer Skills', 'Computer Skills'), ('Numeracy Skills', 'Numeracy Skills')], default='Computer Skills', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='uses',
            field=models.CharField(choices=[('Business Creation', 'Business Creation'), ('Post Creation', 'Post Creation'), ('Agriculture Business', 'Agriculture Business'), ('Startups', 'Startups'), ('Social Business', 'Social Business'), ('Green Business', 'Green Business'), ('Women Entrepreneurship', 'Women Entrepreneurship')], default='Post Creation', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='workshop_method',
            field=models.CharField(choices=[('Online', 'Online'), ('Blended', 'Blended'), ('Presential', 'Presential')], default='Online', max_length=100, null=True),
        ),
    ]
