# Generated by Django 4.1.6 on 2023-04-12 04:13

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_title', models.CharField(max_length=100)),
                ('activity_method', models.CharField(choices=[('Presential', 'Presential'), ('Online', 'Online'), ('Blended', 'Blended')], default='Presential', max_length=100)),
                ('activity_technique', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('activity_difficulty', models.JSONField()),
                ('activity_duration', models.PositiveIntegerField()),
                ('activity_objectives', models.CharField(max_length=100)),
                ('activity_needs', models.TextField(choices=[('Metaplan cards', 'Metaplan cards'), ('Flip cards', 'Flip cards'), ('Pinboard', 'Pinboard'), ('Special facilitation tool', 'Special facilitation tool')], default='Metaplan cards', max_length=100)),
                ('activity_organization', models.CharField(max_length=100)),
                ('activity_variations', models.CharField(max_length=100)),
                ('activity_description', models.CharField(max_length=200, null=True)),
            ],
            options={
                'ordering': ['created_at', 'updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('EASY', 'Easy'), ('INTERMIDIATE', 'Intermidiate'), ('HARD', 'Hard')], default='Easy', max_length=100)),
                ('bgColor', models.CharField(choices=[('ERROR', 'error'), ('WARNING', 'warning'), ('EASY', 'easy')], default='error', max_length=100)),
            ],
        ),
    ]
