# Generated by Django 4.1.6 on 2023-04-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_objectives',
            field=models.TextField(),
        ),
    ]
