# Generated by Django 4.1.6 on 2023-02-11 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workshop', '0010_alter_workshop_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0002_delete_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('activity_title', models.CharField(max_length=100)),
                ('activity_method', models.CharField(max_length=100)),
                ('activity_technique', models.CharField(max_length=100)),
                ('activity_difficulty', models.CharField(max_length=100)),
                ('activity_duration', models.PositiveIntegerField()),
                ('activity_objectives', models.CharField(max_length=100)),
                ('activity_needs', models.TextField(max_length=100)),
                ('activity_organization', models.CharField(max_length=100)),
                ('activity_variations', models.CharField(max_length=100)),
                ('activity_attachements', models.FileField(max_length=200, upload_to='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities_workshop', to='workshop.workshop')),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
    ]
