# Generated by Django 4.1.6 on 2023-02-12 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0011_remove_workshop_workshop_image'),
        ('activity', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities_set', to='workshop.workshop'),
        ),
    ]
