# Generated by Django 4.1.6 on 2023-02-12 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_alter_activity_workshop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_attachements',
        ),
    ]
