# Generated by Django 4.1.6 on 2023-02-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_remove_activity_activity_attachements'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_attachements',
            field=models.FileField(max_length=200, null=True, upload_to='workshopfiles'),
        ),
    ]
