# Generated by Django 4.1.6 on 2023-04-12 23:13

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_alter_activity_activity_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_description',
            field=django_quill.fields.QuillField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_objectives',
            field=django_quill.fields.QuillField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_organization',
            field=django_quill.fields.QuillField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_title',
            field=django_quill.fields.QuillField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_variations',
            field=django_quill.fields.QuillField(null=True),
        ),
    ]
