# Generated by Django 4.1.6 on 2023-04-12 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_alter_activity_activity_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_objectives',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_organization',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_variations',
            field=models.TextField(null=True),
        ),
    ]
