# Generated by Django 4.1.6 on 2023-04-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_alter_activity_activity_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='attch',
            field=models.FileField(null=True, upload_to='workshopattachements/'),
        ),
    ]
