# Generated by Django 4.1.6 on 2023-02-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_remove_activity_activity_attachements'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='day_index',
            field=models.SmallIntegerField(null=True),
        ),
    ]
