# Generated by Django 4.1.6 on 2023-04-13 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_activity_attch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='attch',
        ),
    ]
