# Generated by Django 4.1.6 on 2023-02-13 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
        ('activity', '0008_activity_day_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='workshop',
        ),
        migrations.AddField(
            model_name='activity',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities_set', to='session.session'),
        ),
    ]
