# Generated by Django 4.1.6 on 2023-02-13 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_remove_activity_workshop_activity_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='day_index',
            new_name='position',
        ),
    ]
