# Generated by Django 4.1.6 on 2023-04-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_remove_activity_attch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_method',
            field=models.CharField(choices=[('Presential', 'Presential'), ('Online', 'Online'), ('Blended', 'Blended')], default='Presential', max_length=200),
        ),
    ]
