# Generated by Django 4.1.6 on 2023-02-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_rename_day_index_activity_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='position',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_id',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='laneId',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
