# Generated by Django 4.1.6 on 2023-02-25 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_alter_session_workshop'),
        ('activity', '0011_remove_activity_position_activity_activity_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='laneId',
        ),
        migrations.AlterField(
            model_name='activity',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='session.session'),
        ),
    ]
