# Generated by Django 4.1.6 on 2023-02-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_remove_activity_laneid_alter_activity_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
