# Generated by Django 4.1.6 on 2023-02-26 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0013_activity_activity_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_id',
        ),
    ]
