# Generated by Django 4.1.6 on 2023-02-27 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0015_alter_activity_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['created_at', 'updated_at']},
        ),
    ]
