# Generated by Django 4.1.6 on 2023-02-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0017_alter_activity_activity_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_method',
            field=models.CharField(choices=[('PRESNETIAL', 'Presential'), ('ONLINE', 'Online'), ('BLENDED', 'Blended')], default='Presential', max_length=100),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_needs',
            field=models.TextField(choices=[('BUSINESS_SIMULATION', 'Business simulation'), ('ROLE_PLAY_SIMULATION', 'Role play simulation'), ('ROLE_PLAY', 'Role play'), ('IDEA_GENERATION', 'Idea generation'), ('GROUP_DISCUSSION', 'Group discussion'), ('TEAM_CHALLENGE', 'Team challenge'), ('Multimedia_VIDEO', 'Multimedia, Video'), ('STORY_TELLING_DRAWING', 'Story telling, drawing')], default='Business simulation', max_length=100),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_technique',
            field=models.CharField(choices=[('EASY', 'Easy'), ('INTERMIDIATE', 'Intermidiate'), ('HARD', 'Hard')], default='Easy', max_length=100),
        ),
    ]
