# Generated by Django 4.1.6 on 2023-03-02 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0019_alter_activity_activity_difficulty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('EASY', 'Easy'), ('INTERMIDIATE', 'Intermidiate'), ('HARD', 'Hard')], default='Easy', max_length=100)),
                ('bgColor', models.CharField(choices=[('ERROR', 'error'), ('WARNING', 'warning'), ('EASY', 'easy')], default='error', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_difficulty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.difficulty'),
        ),
    ]
