# Generated by Django 4.1.6 on 2023-03-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0021_alter_activity_activity_needs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_difficulty',
            field=models.CharField(max_length=200),
        ),
    ]
