# Generated by Django 4.1.6 on 2023-03-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0022_alter_activity_activity_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_difficulty',
            field=models.JSONField(),
        ),
    ]
