# Generated by Django 4.1.6 on 2023-03-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0023_alter_activity_activity_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_technique',
            field=models.CharField(choices=[('Business simulation', 'Business simulation'), ('ROLE_PLAY_SIMULATION', 'Role play simulation'), ('ROLE_PLAY', 'Role play'), ('IDEA_GENERATION', 'Idea generation'), ('GROUP_DISCUSSION', 'Group discussion'), ('TEAM_CHALLENGE', 'Team challenge'), ('Multimedia_VIDEO', 'Multimedia, Video'), ('STORY_TELLING_DRAWING', 'Story telling, drawing')], default='Business simulation', max_length=100, null=True),
        ),
    ]
