# Generated by Django 4.1.6 on 2023-03-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0024_alter_activity_activity_technique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_needs',
            field=models.TextField(choices=[('Metaplan cards', 'Metaplan cards'), ('Flip cards', 'Flip cards'), ('Pinboard', 'Pinboard'), ('Special facilitation tool', 'Special facilitation tool')], default='Metaplan cards', max_length=100),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_technique',
            field=models.CharField(choices=[('Business simulation', 'Business simulation'), ('Role play simulation', 'Role play simulation'), ('Role play', 'Role play'), ('Idea generation', 'Idea generation'), ('Group discussion', 'Group discussion'), ('Team challenge', 'Team challenge'), ('Multimedia, Video', 'Multimedia, Video'), ('Story telling, drawing', 'Story telling, drawing')], default='Business simulation', max_length=100, null=True),
        ),
    ]
