# Generated by Django 4.1.6 on 2023-02-13 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0017_remove_workshop_workshop_image'),
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='workshop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions_set', to='workshop.workshop'),
        ),
    ]
