# Generated by Django 4.1.6 on 2023-02-25 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0019_remove_workshop_workshop_image'),
        ('session', '0002_alter_session_workshop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='laneID',
        ),
        migrations.AlterField(
            model_name='session',
            name='workshop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lanes', to='workshop.workshop'),
        ),
    ]
