# Generated by Django 4.1.6 on 2023-02-27 20:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_remove_session_laneid_alter_session_workshop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['created_at', 'updated_at']},
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
