# Generated by Django 4.1.6 on 2023-02-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='difficulty',
            field=models.CharField(choices=[('HARD', 'hard'), ('DIFFICULT', 'difficult'), ('MEDIUM', 'medium'), ('EASY', 'easy'), ('VERY_EASY', 'very easy')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='is_video',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='objective',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='session_description',
            field=models.TextField(null=True),
        ),
    ]
