# Generated by Django 4.1.6 on 2023-02-07 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('session', '0004_session_difficulty_session_is_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='shared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='shared_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='shared_with',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session',
            name='difficulty',
            field=models.CharField(choices=[('HARD', 'hard'), ('DIFFICULT', 'difficult'), ('MEDIUM', 'medium'), ('EASY', 'easy'), ('VERY_EASY', 'very easy')], default='easy', max_length=100, null=True),
        ),
    ]
