# Generated by Django 4.1.6 on 2023-02-27 23:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0005_alter_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
