# Generated by Django 4.1.6 on 2023-02-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imgUrl',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
