# Generated by Django 4.1.6 on 2023-02-05 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_imgurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='imgUrl',
        ),
    ]
