# Generated by Django 4.1.6 on 2023-02-03 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_timestampable_authorable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorable',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='authorable',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='authorable',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Timestampable',
        ),
        migrations.DeleteModel(
            name='Authorable',
        ),
    ]
